---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: debug-statements
          - id: no-commit-to-branch
          - id: check-merge-conflict
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.32.0
      hooks:
          - id: yamllint
    - repo: https://github.com/PyCQA/docformatter
      rev: v1.7.5
      hooks:
          - id: docformatter
    - repo: local
      hooks:
          - id: reorder-python-imports
            name: Reorder Python imports
            entry: reorder-python-imports
            language: python
            types: [python]
          - id: black
            name: Format Python code
            entry: black
            language: python
            types: [python]
